### ISSUE TITLE
Criar pixel art da protagonista

### ISSUE THREAD

**Issue by JVMoreiraD** [Jaofranca/zelda-Like#11]
Deve ser elaborado uma arte da protagonista.

**Comment by Jaofranca** [comment]
![Image](https://github.com/Jaofranca/zelda-Like/assets/50581250/982da416-7e83-45ab-9419-d7b756c3210a)
![Image](https://github.com/Jaofranca/zelda-Like/assets/50581250/d1130c16-fa05-413c-8e2e-393173726d5e)
